name: bridges_login
description: A new Flutter project.
version: 1.0.1+2
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  cloud_firestore: ^2.4.0
  another_flushbar: ^1.10.24

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
