name: bridges_login
description: A new Flutter project.
version: 0.0.5
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.1.0
  firebase_auth: ^3.0.1
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
